version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
    command: streamlit run src/streamlit_app/app.py
